name: Build Component in Native Environment

on:
  pull_request:
    branches: [ develop, main ]
    paths: ['**/*.c', '**/*.cpp', '**/*.cc', '**/*.cxx', '**/*.h', '**/*.hpp', '**/*.sh']

jobs:
  build-rdkfwupdater-on-pr:
    name: Build rdkfwupdater component in github rdkcentral
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rdkcentral/docker-device-mgt-service-test/native-platform:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: native build
        run: |
          chmod +x cov_build.sh
          sh -e cov_build.sh
